[package]
name = "task"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.42.0", features = ["full","macros", "rt-multi-thread"] }
warp = "0.3.7"
serde = { version = "1.0.195", features = ["derive"]}
thiserror = "2.0.12"
chrono = "0.4.39"
anyhow = "1.0.95"
jsonwebtoken = "9.2.0"
wasm-bindgen = "0.2.84"
lazy_static = "1.5.0"
aes = "0.8.4"
aes-gcm = "0.10.3"
base64 = { version = "0.22.1", features = ["alloc"] }
rand = "0.9.0"
surrealdb = "2.1.4"
serde_derive = "1.0.217"
uuid = { version = "1.12.1", features = ["v8"] }
sha2 = "0.10.8"
hex = "0.4.3"
redis = "0.28.1"
log = "0.4.22"
dotenv = "0.15"
tokio-postgres = "0.7.13"
axum = "0.7.7"
serde_json = "1.0.108"
once_cell = "1.19.0"
qdrant-client = "1.13.0"
qdrant = "0.0.0"
# langchain-rust = { version = "4.6.0", features = ["postgres", "qdrant", "surrealdb"] }
langchain-rust = { version = "4.6.0", features = ["surrealdb"] }
tower-http = { version = "0.5.0", features = ["cors"] }
env_logger = "0.11.6"
